# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTY4MGIwYjQzMTc2ZmUyZjkyMjY2NTNmOGU0YTUzN2MzMGM3ODJhMDlkMDhmYTg1ZGEyZDU0NWIxNThlYzVhNWJlY2I3OTE2MTljZjM5NzYzNTE0YWRlYzQzMjk4OTIwMGM0NjNhMmUyNmE0OWVlYzA1MjA4NmQ1ZTJkYzBkY2I=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
